server:
  port: 9000
spring:
  spplication:
    name: zuul-gateway
eureka:
  instance:
    hostname: localhost
  client:serviceUrl:
    defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    ServiceB:
      path: /demo/**